In [1]:
import numpy as np

#### Creating one-dimensional array (Vector)

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
type(a)

numpy.ndarray

#### Creating two-dimentional numpy array (Matrix)

In [7]:
b=np.array([1,2,3],[4,5,6],[7,8,9])
b

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [9]:
b=np.array([[1,2,3],[4,5,6],[7,8,9,10,11]])   #use double sq.brackets
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b=np.array([1,2,3],[4,5,6,7,8])   
b

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [15]:
b=np.array([[1,2,3],[4,5,6,7,8]])   
b                                    #length is different

C:\Users\DELL\AppData\Local\Temp\ipykernel_12488\372316883.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[4,5,6,7,8]])


array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

In [16]:
np.array([1,2,3,4],dtype=float)         # converting data type to float

array([1., 2., 3., 4.])

In [17]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [20]:
np.array([0,2,0,4],dtype=bool)       # additing 0 will give False
 

array([False,  True, False,  True])

In [21]:
np.array([1,2,3,4],dtype=complex)      # converting data type to complex

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10,3)    # 1+3=4, 4+3=7 

array([1, 4, 7])

In [27]:
np.arange(1,15,6)

array([ 1,  7, 13])

In [29]:
np.arange(2,15,18)    # if last value > middle value, result= 1st value; 2

array([2])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
np.arange(10).reshape(5,3)   # error coz we have 10 elements which cannot reshape into (5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [36]:
np.ones(2,5)

TypeError: Cannot interpret '5' as a data type

In [37]:
np.ones((2,5))   #use double brackets

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.zeros((2,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
np.ones((2,5), int) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.random.rand(2,4)

array([[0.50472352, 0.62604968, 0.33369742, 0.11775529],
       [0.31697339, 0.66915843, 0.39057691, 0.02376422]])

In [45]:
np.random.randn(2,4)      # getting normal distribution

array([[-2.48899709e-01, -9.85130638e-01,  2.30665441e+00,
         9.43108384e-01],
       [ 1.28735436e+00, -7.99539906e-02,  2.02535946e-03,
         1.27213939e+00]])

In [49]:
np.random.randint(2,50)    #random int bet 2 to 50

40

In [51]:
np.linspace(0,2,5) # five equal parts

array([0. , 0.5, 1. , 1.5, 2. ])

In [52]:
np.linspace(-5,2,5) 

array([-5.  , -3.25, -1.5 ,  0.25,  2.  ])

In [55]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a2=np.arange(10,dtype= float)
a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
a2=a2.reshape(2,5)
a2

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [62]:
a3=np.arange(8).reshape(2,2,2)
a3                             # 2 sets, 2 rows, 2  cols

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a4=np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a1.ndim 

1

In [68]:
a2.ndim   #2 dimension

2

In [69]:
a3.ndim    #2 dimension

3

In [70]:
a1.shape

(10,)

In [71]:
a2.shape

(2, 5)

In [74]:
a3.shape

(2, 2, 2)

In [75]:
a4.shape

(3, 3, 3)

In [76]:
a1.size

10

In [77]:
a2.size

10

In [78]:
a3.size

8

In [79]:
a4.size

27

### Changing Data Type

In [80]:
x=np.array([2,1,6,3.7])

In [81]:
x

array([2. , 1. , 6. , 3.7])

In [82]:
x.astype(int)   #not rounding off only considering integer part

array([2, 1, 6, 3])

In [83]:
x.astype(bool)

array([ True,  True,  True,  True])

In [84]:
x=np.array([2,1,0,3.7])
x.astype(bool)

array([ True,  True, False,  True])

In [85]:
a=np.arange(6).reshape(2,3)

In [86]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
a+2

array([[2, 3, 4],
       [5, 6, 7]])

In [88]:
a*6

array([[ 0,  6, 12],
       [18, 24, 30]])

In [90]:
a//2

array([[0, 0, 1],
       [1, 2, 2]], dtype=int32)

In [91]:
a%3

array([[0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [92]:
a>3

array([[False, False, False],
       [False,  True,  True]])

In [99]:
b=np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
a+b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [101]:
a+b>5

array([[False, False, False],
       [ True,  True,  True]])

In [105]:
c=np.random.random((3,3))
c

array([[0.27746154, 0.08572128, 0.64970161],
       [0.59750698, 0.39287877, 0.1921226 ],
       [0.01960068, 0.19352985, 0.4047221 ]])

In [106]:
d=np.round(c*100)

In [107]:
d

array([[28.,  9., 65.],
       [60., 39., 19.],
       [ 2., 19., 40.]])

In [108]:
np.max(d)

65.0

In [109]:
np.min(d)

2.0

In [110]:
np.sum(d)

281.0

In [111]:
np.prod(d)

1106947296000.0

In [112]:
np.var(d)

418.1728395061728

In [114]:
np.max(d, axis=1)    #max value of rows

array([65., 60., 40.])

In [115]:
np.min(d, axis=1) 

array([ 9., 19.,  2.])

In [116]:
np.max(d, axis=0)  #max value of colomns

array([60., 39., 65.])

In [117]:
np.prod(d, axis=0)    #colomn-wise multiplication

array([ 3360.,  6669., 49400.])

In [118]:
np.mean(d)

31.22222222222222

In [119]:
np.mean(d, axis=0)

array([30.        , 22.33333333, 41.33333333])

In [120]:
np.median(d, axis=0)

array([28., 19., 40.])

In [122]:
np.sin(d)

array([[ 0.27090579,  0.41211849,  0.82682868],
       [-0.30481062,  0.96379539,  0.14987721],
       [ 0.90929743,  0.14987721,  0.74511316]])

In [123]:
np.cos(d)

array([[-0.96260587, -0.91113026, -0.56245385],
       [-0.95241298,  0.26664293,  0.98870462],
       [-0.41614684,  0.98870462, -0.66693806]])