# Numpy is a package which is helpful to play with numbers

In [1]:
import numpy as np

In [2]:
simple_list= [8,9,10]
np.array(simple_list)

array([ 8,  9, 10])

In [4]:
arr= np.array([2,5,6])
arr

array([2, 5, 6])

In [6]:
list_of_Lists= [[2,4,5], [9,10,12], [23,24,88]]
np.array(list_of_Lists)

array([[ 2,  4,  5],
       [ 9, 10, 12],
       [23, 24, 88]])

In [7]:
np.arange(6,20)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(2,30,3)     # shift+tab-> help box

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [10]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(12,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((2,6), int)    # this will give two rows and six coloumns of ones

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((2,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.linspace(0,3,6)    #linear space

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [21]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [22]:
np.eye(9)   #diagonal 9*9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(9,12)      # random numbers between 0 to 1 in 9rows and 12 col

array([[0.14085497, 0.27475632, 0.11007459, 0.83065259, 0.33705405,
        0.44606716, 0.26286555, 0.03792788, 0.50921162, 0.88675162,
        0.04684434, 0.76409828],
       [0.29063508, 0.6827317 , 0.64170086, 0.37494428, 0.34780943,
        0.52897418, 0.98594774, 0.20270544, 0.25653983, 0.17274844,
        0.90228938, 0.05721004],
       [0.05077414, 0.66867442, 0.32038321, 0.53747167, 0.24275566,
        0.34700758, 0.23561148, 0.07480769, 0.20814972, 0.67522976,
        0.15133518, 0.28897369],
       [0.54453936, 0.73853342, 0.44549716, 0.63134379, 0.31880462,
        0.46170077, 0.56140221, 0.09032372, 0.00816123, 0.38982003,
        0.30011552, 0.50079941],
       [0.58906701, 0.2681146 , 0.79832522, 0.24557887, 0.36556771,
        0.30771105, 0.20485665, 0.95254816, 0.43675644, 0.61352421,
        0.64553302, 0.3243091 ],
       [0.07473958, 0.6558573 , 0.74635542, 0.0467952 , 0.7726005 ,
        0.49161864, 0.30482689, 0.9913395 , 0.85714946, 0.36018972,
        0.58493153,

In [26]:
arr= np.random.randn(3,5)
arr

array([[-0.8855325 , -1.43417128,  0.88590721,  0.94489185,  0.25846781],
       [-0.94431654, -0.18502543,  0.98644238,  0.04500056,  0.90854014],
       [-1.49517124, -0.04067788,  0.14841536, -1.48472638, -0.04032899]])

In [28]:
sample_array= np.arange(18)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [31]:
rand_array=np.random.randint(2,8,29)
rand_array

array([7, 7, 2, 4, 5, 4, 5, 7, 3, 2, 7, 7, 6, 3, 2, 3, 2, 2, 7, 6, 6, 5,
       7, 3, 6, 3, 5, 3, 4])

In [32]:
sample_array.reshape(8,12)

ValueError: cannot reshape array of size 18 into shape (8,12)

In [33]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 18 into shape (4,3)

In [34]:
np.random.randint(2,50)   #any random integer between 2 to 50

39

In [37]:
rand_array.max()

7

In [39]:
rand_array.min()

2

In [41]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
a.T    #transpose

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
a = np.random.rand(3,5)
a

array([[0.60744609, 0.96175661, 0.36337657, 0.70433212, 0.63353502],
       [0.86490182, 0.84115704, 0.35188252, 0.1544223 , 0.13697255],
       [0.47204375, 0.77586865, 0.14781292, 0.7976025 , 0.26380541]])

In [45]:
a = np.random.rand(5,2)
a

array([[0.28515322, 0.18595785],
       [0.21668692, 0.95702465],
       [0.13019949, 0.88030409],
       [0.93800167, 0.53914635],
       [0.55549147, 0.19474357]])

In [47]:
sample_array=np.arange(12,18)
sample_array

array([12, 13, 14, 15, 16, 17])

In [48]:
sample_array[0]

12

In [49]:
sample_array[3:5]   #will give third and fourth elem

array([15, 16])

In [56]:
sample_array[2:5]=80    #replacing the 2nd,3rd and 4th element of sample_array by 80
sample_array

array([10, 11, 80, 80, 80, 15, 16, 17, 18, 19])

In [55]:
sample_array= np.arange(10,20)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Two dimentional array

In [57]:
sample_matrix=np.array(([10,7,12],[18,12,2],[23,56,74]))
sample_matrix

array([[10,  7, 12],
       [18, 12,  2],
       [23, 56, 74]])

In [58]:
sample_matrix[1,2] #common element of 1st row and 2nd col

2

In [60]:
sample_matrix[2,:] #Whole row

array([23, 56, 74])

In [62]:
sample_matrix[2]

array([23, 56, 74])

In [65]:
sample_matrix[:,(2,2)]

array([[12, 12],
       [ 2,  2],
       [74, 74]])

### Selection Techniques

In [67]:
sample_array=np.arange(2,12)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
sample_array + sample_array    #adding matrix

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [69]:
np.exp(sample_array) #exponential

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04])

In [70]:
np.sqrt(sample_array) #square root

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479])

In [71]:
np.log(sample_array)   #logrithm

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527])

In [72]:
np.max(sample_array)

11

In [73]:
np.min(sample_array)

2

In [74]:
np.square(sample_array)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [75]:
np.std(sample_array) #standard deviation

2.8722813232690143

In [76]:
np.var(sample_array)    #variance

8.25

In [77]:
np.mean(sample_array)

6.5

In [81]:
array=np.random.randn(2,3)
array

array([[ 0.66779436, -1.37047522, -0.66994232],
       [-1.50582946, -0.11246443, -0.86369708]])

In [82]:
np.round(array,decimals=2)   #rounding off the array

array([[ 0.67, -1.37, -0.67],
       [-1.51, -0.11, -0.86]])

In [84]:
sports=np.array(['golf','cricket','hockey','badminton','cricket'])   #arranged alphabetically
np.unique(sports)

array(['badminton', 'cricket', 'golf', 'hockey'], dtype='<U9')